---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rcchedqz/public_html/
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/index.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/about.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/programs.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/who-we-serve.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/voices.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/contact.html $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/styles.css $DEPLOYPATH
    - /bin/cp -f /home/rcchedqz/repositories/fbc-website1/script.js $DEPLOYPATH
    - /bin/cp -R /home/rcchedqz/repositories/fbc-website1/public/* $DEPLOYPATH
