---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rcchedqz/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp programs.html $DEPLOYPATH
    - /bin/cp who-we-serve.html $DEPLOYPATH
    - /bin/cp voices.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
